#===================================================================================================
# Copyright © 2018 nanorep.
# NanorepUI SDK.
# All rights reserved.
#===================================================================================================

platform :ios, "9.0"
use_frameworks!

# Uncomment to use a local copy of PlayKit
#BLD_UI="../../../BoldUI/BoldUI-Dev.podspec"
BLD_CORE="../../../BoldCore/BoldCore-Dev.podspec"
BLD_AI_ENGINE="../../../BoldAIEngine/BoldAIEngine-Dev.podspec"
BLD_AI_ACCESSIBILITY="../../../BoldAIAccessibility/BoldAIAccessibility-Dev.podspec"
BLD_ENGINE="../../../Bold/BoldEngine/BoldEngine-Dev.podspec"
BLD_360_AI="../../../Bold360AI/Bold360AI-Dev.podspec"

# Dev
source 'https://github.com/nanorepsdk/NRSDK-Dev-specs.git'
# Production
#source 'https://github.com/nanorepsdk/NRSDK-specs.git'

source 'https://github.com/CocoaPods/Specs'

target 'BasicSample' do
    if defined? BLD_UI 
        pod 'BoldCore', :path => BLD_CORE
        pod 'BoldAIEngine', :path => BLD_AI_ENGINE
        pod 'BoldAIAccessibility', :path => BLD_AI_ACCESSIBILITY
        pod 'BoldEngine', :path => BLD_ENGINE
        pod 'BoldUI', :path => BLD_UI
       pod 'Bold360AI', :path => BLD_360_AI
        pod 'RealmSwift'
    else
        pod 'Bold360AI'
        pod 'RealmSwift'
    end
end
